name: Update README with NASA's picture of the day and stats

on:
  # push:
  workflow_dispatch:
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onschedule
  schedule:
    # every 5 minutes for testing
    # - cron: '*/5 * * * *'
    # each day at 5:00  (UTC)
    - cron: "0 5 * * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm i

      - name: Update README.md file
        env:
          NASA_API_KEY: ${{ secrets.NASA_API_KEY }}
        run:
          node update.js
          # > README.md
        continue-on-error: true

      - name: Commit and push
        # https://docs.github.com/en/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |-
          git diff
          git config --global user.email "tempo2riz@gmail.com"
          git config --global user.name "tempo-riz"
          echo " " >> README.md
          git commit -am "readme updated by workflow" || exit 0
          git push
