name: Update README with NASA's picture of the day

on:
  push:
  workflow_dispatch:
  schedule:
    # each day at 8:00
    - cron: '0 8 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm i

      - name: Update README.md file
        env:
          NASA_API_KEY: ${{ secrets.NASA_API_KEY }}
        run: node update.js 
          # > README.md

      - name: Commit and push if changed
        # https://docs.github.com/en/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |-
            git diff
            git config --global user.email "tempo2riz@gmail.com"
            git config --global user.name "tempo-riz"
            git commit -am "readme updated" || exit 0
            git push

      